name: Java Maven Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: contactekansh/github-workflows-template/.github/workflows/test.yml@main
